### PR TITLE
Fix auth sinon stub

### PR DESCRIPTION
**Pull request by corlaez**
~Two~ things caused problems:
1. The way auth.session method was passed directly into express would not let sinon work as expected:
https://gist.github.com/corlaez/12382f97b706c964c24c6e70b45a4991
https://github.com/corlaez/mocha_stub_server/blob/createApp/createApp.js#L11

2. ~The server creation needs to be a separate step (`init`). That prevents getting the problem where each test is trying to create a server (address in use).~ (we don't need to do this to make your integration tests pass but I still recommend this)

Commits:
A lot of the commits it's just to prepare the environment, or some accessory adjustments after the fix. The important commits are:
https://github.com/DashBarkHuss/mocha_stub_server/pull/1/commits/59af8c2a9abc1a30f1165a0ad41a2ff81c64ec61 where I change the code to use createApp (but creates and destroys the server again and again)
https://github.com/DashBarkHuss/mocha_stub_server/pull/1/commits/bc18052ace34a4568b8d01cd46fd8c570d44f374 Where Auth Sinon problem is fixed and initialization of the server separated. Which means a single server is created for all tests and auth stubbing works as expected.
https://github.com/DashBarkHuss/mocha_stub_server/pull/1/commits/b49961060c399989579418ca36ffee45ad9b2990 Avoid passing auth explicitly and delete unneeded files

### CODE REVIEW

**Comment by DashBarkHuss** [comment]
Thanks for this. There's one thing I don't understand though. In a real application, you will have more than just `auth` that you might want to stub. You will have hundreds or thousands of functions. Are they all supposed to be passed in this way? And if not, they can't be stubbed? That doesn't seem right. I can't imagine calling `createApp(auth, StripeService, StripeAPInterface, etc...for every function in the app... );`

**Comment by corlaez** [comment]
You can get away without passing the dependencies explicitly, I added a commit showing how that looks like.

**Comment by corlaez** [comment]
So in reality there was just one problem (the one listed as number one in the description).
Even if we don't have init as a separate step we can make this work.
However, I still recommend init to be a separate step in case you want to have a different script for unit tests. That unit test script wouldn't --require the server initialization.

**Comment by corlaez** [comment]
feel free to close this, I bet this might be irrelevant by now.

**Pull request closed without merging**
